### PR TITLE
Fix #4 and maybe #7

### LINKED ISSUE #4: .env file sample
Create a sample .env file or maybe even just include a code box [here](https://github.com/jacktrip-webrtc/jacktrip-webrtc/blob/develop-datachannel/documentation/Configuration.md) with a sample of what the .env file will look like.

Also, if HTTP defaults to true, and HTTPS defaults to true, which one is it using by default?

O

### PR DESCRIPTION
**Pull request by omarcostahamido**
this fixes #4 
there were other phrasing improvements.
please @matteosacchetto review and merge.

### CODE REVIEW

**Comment by omarcostahamido** [comment]
this also refers to #2

**Comment by omarcostahamido** [comment]
this may also fix #7 for the time being.

**Comment by omarcostahamido** [comment]
Yes. Agreed.
Thanks

**Comment by matteosacchetto** [comment]
Hi Omar, just a question: did you push something to this repo yesterday?  
I was wondering that because yesterday I performed a sqash merge, in order to keep the repo clean, but today I found the commits related to this pull request also as regular commits. Since i do not have them on my local copy I was wondering how did it happen.

Cheers,
Matteo

**Comment by omarcostahamido** [comment]
I updated my fork yesterday...
Had one conflict in config.md.
But that should not influence the main repo, does it?

O

**Comment by omarcostahamido** [comment]
Huh, apparently it did add two blank lines to that file,
yes: 1dda4dd580840caa34f35554055158c9fe63b7db

How can I help fix the problem?

O

**Comment by matteosacchetto** [comment]
Well, actually I do not know if we can fix it 😅 ... I think that once it is pushed to the repo fixing it is quite difficult/not possible. It should not be a problem since when we will merge with the master I will perform a squash merge, anyway if I find something on how to fix this i will tell you 😉 

I just ask you to pay a bit more attention in the future, so that we are able to keep this repo cleaner.
Thanks, and cheers

Matteo

**Comment by omarcostahamido** [comment]
Yes my apologies.
I know of a way... but it is bit overkill for something like this: it
involves cherry picking and recreating the branch.
What is the error message on your end?
Does it give you an option to resolve conflict?

O

**Comment by omarcostahamido** [comment]
We can also try reverting that last commit. In effect it does create an
additional commit in history but it will put that file in the same state it
was before.
(Btw, you do realize we are talking about a commit with 2 blank lines,
right? :D)

O

**Comment by matteosacchetto** [comment]
Hi Omar, there are no problems/conflicts on my end (i think 😅). I think that we can leave everything as is 😃.  
The thing that caught my attention was not the last commit, it is fine as a commit :), but i noticed that some older commits appeared, and those commit seemed to not be directly related to this repo, but actually to your fork, so I wondered how did they appear. For example: 74d80c7514a2877b342ed70ddb121135dffba318, d7ee086c071c92be1d9269d3282de3b44d53a778.

That is why I asked you if you pushed something, because they seemed to appear between my and your last push.

Cheers,
Matteo

**Comment by omarcostahamido** [comment]
Hum... that's strange. Github is a mystery 😅 
So the first one is from [noah's PR](https://github.com/jacktrip-webrtc/jacktrip-webrtc/pull/3).
The second one... is me [updating](https://github.com/omarcostahamido/jacktrip-webrtc/pulls?q=is%3Apr+is%3Aclosed) MY fork 3 days ago... now why does it appear on the history of the main repo? Maybe because [my single PR](https://github.com/jacktrip-webrtc/jacktrip-webrtc/pull/8) to this repo 2 days ago included all the the new changes my fork had (including me updating it)?
How do you keep a fork updated? I'm always keen to learn better and cleaner github workflows.

Thx,
OCH

**Comment by matteosacchetto** [comment]
> Maybe because [my single PR](https://github.com/jacktrip-webrtc/jacktrip-webrtc/pull/8) to this repo 2 days ago included all the the new changes my fork had (including me updating it)?  

Well, the fact is that when I merged the PR, I performed a squash merge, that combines all the commits into a new commit, so, after the PR has been merged, the different commits are not included in the history of the destination branch, but only the merge commit is present. So i think that somethig else happened, but I do not know what exactly... 🤷‍♂️

> How do you keep a fork updated?  

I actually never managed a fork here on GitHub, so I don't know 😅

**Pull request merged**
